version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./frontend-frota
    ports:
      - "80:80"
    depends_on:
      - backend
