version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./frota.db:/app/frota.db  # Monta o banco diretamente na raiz do container
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./frontend-frota
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
