version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - sqlite-data:/app/data  # Volume para persistir dados do SQLite
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./frontend-frota
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  sqlite-data: